//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Biblioteca.java
//  @ Date : 20/08/2026
//  @ Author : 
//
//


import java.util.List;
import java.util.ArrayList;

public class Biblioteca {

    private List<Prestamo> prestamos;

    public Biblioteca() {
        prestamos = new ArrayList<Prestamo>();
    }

    public Prestamo buscarPrestamo(int codigo) {

        for (int i = 0; i < prestamos.size(); i++) {
            if (prestamos.get(i).getCodigoPrestamo() == codigo) {
                return prestamos.get(i);
            }
        }
        return null;
    }

    public void agregarPrestamo(Prestamo prestamo) {
        if (buscarPrestamo(prestamo.getCodigoPrestamo()) == null) {
            prestamos.add(prestamo);
        }
    }


    public void mostrarPrestamos() {
        for (int i = 0; i < prestamos.size(); i++) {
            Prestamo prestamo = prestamos.get(i);

            System.out.println("Código: " + prestamo.getCodigoPrestamo());
            System.out.println("Carné: " + prestamo.getCarneEstudiante());
            System.out.println("Estudiante: " + prestamo.getNombreEstudiante());
            System.out.println("Libro: " + prestamo.getTituloLibro());
            System.out.println("Días autorizados: " + prestamo.getDiasAutorizados());
            System.out.println();
        }
    }

    public void modificarPrestamo(int codigo, String nuevoTitulo, int nuevosDias) {
        Prestamo prestamo = buscarPrestamo(codigo);

        if (prestamo != null) {

            prestamo.setTituloLibro(nuevoTitulo);
            prestamo.setDiasAutorizados(nuevosDias);
        }
    }

    public void eliminarPrestamo(int codigo) {
        Prestamo prestamo = buscarPrestamo(codigo);
        if (prestamo != null) {
            prestamos.remove(prestamo);
        }
    }

    public void mostrarPrestamosEstudiante(int carne) {
        boolean encontrado = false;
        for (int i = 0; i < prestamos.size(); i++) {

            Prestamo prestamo = prestamos.get(i);

            if (prestamo.getCarneEstudiante() == carne) {

                encontrado = true;

                System.out.println("Código: " + prestamo.getCodigoPrestamo());
                System.out.println("Carné: " + prestamo.getCarneEstudiante());
                System.out.println("Estudiante: " + prestamo.getNombreEstudiante());
                System.out.println("Libro: " + prestamo.getTituloLibro());
                System.out.println("Días autorizados: " + prestamo.getDiasAutorizados());
                System.out.println();
            }
        }
        if (!encontrado) {
            System.out.println(
                    "No se encontraron préstamos para ese estudiante."
            );
        }
    }

    public int totalDiasAutorizados() {
        int total = 0;
        for (int i = 0; i < prestamos.size(); i++) {
            total += prestamos.get(i).getDiasAutorizados();
        }
        return total;
    }

    public Prestamo mayorDuracion() {
        Prestamo mayor = null;
        for (int i = 0; i < prestamos.size(); i++) {
            if (mayor == null || prestamos.get(i).getDiasAutorizados() > mayor.getDiasAutorizados()) {
                mayor = prestamos.get(i);
            }
        }
        return mayor;
    }

    public int cantidadPrestamos() {
        return prestamos.size();
    }
}