//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Prestamo.java
//  @ Date : 20/08/2026
//  @ Author : 
//
//

public class Prestamo {

    private int codigoPrestamo;
    private int carneEstudiante;
    private String nombreEstudiante;
    private String tituloLibro;
    private int diasAutorizados;

    public Prestamo() {

        codigoPrestamo = 0;
        carneEstudiante = 0;
        nombreEstudiante = "Nombre";
        tituloLibro = "Libro";
        diasAutorizados = 0;
    }

    public void setCodigoPrestamo(int newCodigo) {
        codigoPrestamo = newCodigo;
    }

    public int getCodigoPrestamo() {
        return codigoPrestamo;
    }

    public void setCarneEstudiante(int newCarne) {
        carneEstudiante = newCarne;
    }

    public int getCarneEstudiante() {
        return carneEstudiante;
    }

    public void setNombreEstudiante(String newNombre) {
        nombreEstudiante = newNombre;
    }

    public String getNombreEstudiante() {
        return nombreEstudiante;
    }

    public void setTituloLibro(String newTitulo) {
        tituloLibro = newTitulo;
    }

    public String getTituloLibro() {
        return tituloLibro;
    }

    public void setDiasAutorizados(int newDias) {
        diasAutorizados = newDias;
    }

    public int getDiasAutorizados() {
        return diasAutorizados;
    }
}