//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Principal.java
//  @ Date : 20/08/2026
//  @ Author : 
//
//

import java.util.Scanner;

public class Principal {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Biblioteca biblioteca = new Biblioteca();
        boolean continuar = true;
        while (continuar) {

            System.out.println("MENÚ DE BIBLIOTECA");
            System.out.println("1. Registrar préstamo");
            System.out.println("2. Consultar préstamos");
            System.out.println("3. Buscar préstamo");
            System.out.println("4. Modificar préstamo");
            System.out.println("5. Registrar devolución");
            System.out.println("6. Consultar préstamos por estudiante");
            System.out.println("7. Reporte de días autorizados");
            System.out.println("8. Préstamo con mayor duración");
            System.out.println("9. Cantidad de préstamos");
            System.out.println("10. Salir");
            System.out.print("\nSeleccione una opción: ");

            int opcion = 0;
            try {

                opcion = scanner.nextInt();
                scanner.nextLine();

            } catch (Exception e) {
                System.out.println("Ingrese un número");
                scanner.nextLine();
            }
            if (opcion < 1 || opcion > 10) {
                System.out.println("Opción inválida. Ingrese un número del 1 al 10.");
            } else {
                switch (opcion) {

                    case 1:

                        System.out.println("REGISTRO DE PRÉSTAMO");

                        Prestamo nuevoPrestamo = new Prestamo();
                        System.out.print("Ingrese el código del préstamo: ");
                        int codigo = scanner.nextInt();
                        scanner.nextLine();
                        while (biblioteca.buscarPrestamo(codigo) != null) {
                            System.out.println(
                                    "Ese código ya se encuentra registrado."
                            );
                            System.out.print(
                                    "Ingrese otro código: "
                            );
                            codigo = scanner.nextInt();
                            scanner.nextLine();
                        }
                        nuevoPrestamo.setCodigoPrestamo(codigo);

                        System.out.print("Ingrese el carné del estudiante: ");
                        int carne = scanner.nextInt();
                        scanner.nextLine();

                        while (carne <= 0) {
                            System.out.println("Carné inválido.");
                            System.out.print("Ingrese nuevamente: ");

                            carne = scanner.nextInt();
                            scanner.nextLine();
                        }

                        nuevoPrestamo.setCarneEstudiante(carne);
                        System.out.print("Ingrese el nombre del estudiante: ");
                        String nombreEstudiante = scanner.nextLine();

                        while (nombreEstudiante.isEmpty()) {
                            System.out.println("El nombre no puede estar vacío.");
                            System.out.print("Ingrese nuevamente: ");
                            nombreEstudiante = scanner.nextLine();
                        }

                        nuevoPrestamo.setNombreEstudiante(nombreEstudiante);

                        System.out.print("Ingrese el título del libro: ");
                        String titulo = scanner.nextLine();
                        while (titulo.isEmpty()) {
                            System.out.println("Ingrese un título");
                            titulo = scanner.nextLine();
                        }
                        nuevoPrestamo.setTituloLibro(titulo);

                        System.out.print("Ingrese los días autorizados: ");
                        int dias = scanner.nextInt();
                        scanner.nextLine();

                        while (dias <= 0) {
                            System.out.print("Cantidad de días debe ser un entero positivo. Ingrese nuevamente: ");
                            dias = scanner.nextInt();
                            scanner.nextLine();
                        }

                        nuevoPrestamo.setDiasAutorizados(dias);
                        biblioteca.agregarPrestamo(nuevoPrestamo);

                        System.out.println("Préstamo registrado correctamente.");
                        break;

                    case 2:
                        System.out.println("PRÉSTAMOS REGISTRADOS");
                        if (biblioteca.cantidadPrestamos() > 0) {
                            biblioteca.mostrarPrestamos();
                        } 
						else {
                            System.out.println("No hay préstamos registrados.");
                        }
                        break;
                    case 3:

                        System.out.println("BUSCAR PRÉSTAMO");

                        try {
                            System.out.print("Ingrese el código del préstamo: ");
                            int codigoBuscar = scanner.nextInt();
                            scanner.nextLine();
                            Prestamo prestamoEncontrado =
                                    biblioteca.buscarPrestamo(
                                            codigoBuscar
                                    );
                            if (prestamoEncontrado != null) {
                                System.out.println("Código: " + prestamoEncontrado.getCodigoPrestamo());
								System.out.println("Carné: " + prestamoEncontrado.getCarneEstudiante());
                                System.out.println("Estudiante: " + prestamoEncontrado.getNombreEstudiante());
                                System.out.println("Libro: " + prestamoEncontrado.getTituloLibro());
                                System.out.println("Días autorizados: " + prestamoEncontrado.getDiasAutorizados());
                            } 
							else {
                                System.out.println("Préstamo no encontrado.");
                            }
                        } 
						catch (Exception e) {
                            System.out.println("Entrada inválida, el código debe ser un número");
                            scanner.nextLine();
                        } 
						finally {
                            System.out.println("Búsqueda finalizada.");
                        }
                        break;

                    case 4:
                        System.out.println("MODIFICAR PRÉSTAMO");
                        System.out.print("Ingrese el código del préstamo: ");
                        int codigoModificar = scanner.nextInt();
                        scanner.nextLine();
                        Prestamo prestamoModificar = biblioteca.buscarPrestamo(codigoModificar);

                        if (prestamoModificar != null) {
                            System.out.print("Ingrese el nuevo título del libro: ");
                            String nuevoTitulo = scanner.nextLine();
                            while (nuevoTitulo.isEmpty()) {
                                System.out.println("Coloque un título. Ingrese nuevamente. ");
                                nuevoTitulo = scanner.nextLine();
                            }

                            System.out.print("Ingrese los nuevos días autorizados: ");
                            int nuevosDias = scanner.nextInt();
                            scanner.nextLine();
                            while (nuevosDias <= 0) {
                                System.out.print("Días deben ser mayores a 0. Ingrese nuevamente: ");
                                nuevosDias = scanner.nextInt();
                                scanner.nextLine();
                            }

                            biblioteca.modificarPrestamo(
                                    codigoModificar,
                                    nuevoTitulo,
                                    nuevosDias
                            );
                            System.out.println(
                                    "Préstamo modificado correctamente."
                            );
                        } else {
                            System.out.println(
                                    "Préstamo no encontrado."
                            );
                        }
                        break;

                    case 5:
                        System.out.println("DEVOLUCIÓN");
                        System.out.print("Ingrese el código del préstamo: ");

                        int codigoEliminar = scanner.nextInt();
                        scanner.nextLine();
                        Prestamo prestamoEliminar =biblioteca.buscarPrestamo(codigoEliminar);

                        if (prestamoEliminar != null) {
                            biblioteca.eliminarPrestamo(codigoEliminar);
                            System.out.println("Devolución registrada correctamente.");
                        } 
						else {
							System.out.println("Préstamo no encontrado.");
                        }
                        break;

                    case 6:
                        System.out.println("PRÉSTAMO DE ESTUDIANTE");

                        System.out.print("Ingrese el código del estudiante: ");
                        int carneBuscar = scanner.nextInt();
                        scanner.nextLine();
                        biblioteca.mostrarPrestamosEstudiante(carneBuscar);
                        break;

                    case 7:
                        System.out.println("REPORTE DE DÍAS");
                        System.out.println("Total de días autorizados: " + biblioteca.totalDiasAutorizados());
                        break;

                    case 8:
                        System.out.println("MAYOR DURACIÓN DE DÍAS");
                        Prestamo prestamoMayor = biblioteca.mayorDuracion();
                        if (prestamoMayor != null) {
                            System.out.println("Código: "+ prestamoMayor.getCodigoPrestamo());
                            System.out.println("Carné: " + prestamoMayor.getCarneEstudiante());
                            System.out.println("Estudiante: " + prestamoMayor.getNombreEstudiante());
                            System.out.println("Libro: " + prestamoMayor.getTituloLibro());
                            System.out.println("Días autorizados: " + prestamoMayor.getDiasAutorizados());
                        } 
						else {
                            System.out.println("No hay préstamos registrados.");
                        }
                        break;

                    case 9:
                        System.out.println("CANTIDAD DE PRÉSTAMOS");
                        System.out.println("Préstamos registrados: "+ biblioteca.cantidadPrestamos());
                        break;

                    case 10:
                        continuar = false;
                        break;
                }
            }
        }

        scanner.close();
    }
}