//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : main.java
//  @ Date : 12/08/2026
//  @ Author : 
//
//

import java.util.Scanner;

public class main {

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);

        System.out.println("-----SISTEMA DE PELÍCULAS-----");

        System.out.print("Ingrese su nombre: ");
        String nombre = scanner.nextLine();

        System.out.print("Ingrese su nombre de usuario: ");
        String nombreUsuario = scanner.nextLine();

        System.out.print("Ingrese su edad: ");
        int edad = scanner.nextInt();
        scanner.nextLine();

        Usuario usuario = new Usuario(nombre, nombreUsuario, edad);

        boolean continuar = true;

        while (continuar) {

            System.out.println("-----MENÚ------");

            System.out.println("1. Nuevo usuario");
            System.out.println("2. Registrar nueva calificación");
            System.out.println("3. Consultar calificaciones");
            System.out.println("4. Consultar una película");
            System.out.println("5. Modificar calificación");
            System.out.println("6. Mostrar promedio");
            System.out.println("7. Mostrar mejor y peor calificación");
            System.out.println("8. Consultar espacios disponibles");
            System.out.println("9. Salir");

            System.out.print("\nSeleccione una opción: ");
            int opcion = scanner.nextInt();
            scanner.nextLine();

            // Validación de la opción

            while (opcion < 1 || opcion > 9) {

                System.out.println("Opción inválida.");
                System.out.print("Ingrese nuevamente: ");

                opcion = scanner.nextInt();
                scanner.nextLine();
            }

            switch (opcion) {
                case 1:

                    System.out.println("\n----- NUEVO USUARIO -----");

                    System.out.print("Ingrese su nombre: ");
                    nombre = scanner.nextLine();

                    System.out.print("Ingrese su nombre de usuario: ");
                    nombreUsuario = scanner.nextLine();

                    System.out.print("Ingrese su edad: ");
                    edad = scanner.nextInt();
                    scanner.nextLine();

                    usuario = new Usuario(nombre, nombreUsuario, edad );

                    System.out.println("Nuevo usuario creado.");
                    break;

                case 2:

                    if (usuario.espDisp() > 0) {

                        System.out.println("\n----- NUEVA PELÍCULA -----");

                        System.out.print("Nombre de la película: ");
                        String nombrePeli = scanner.nextLine();

                        System.out.print("Calificación (1 - 10): ");
                        int nota = scanner.nextInt();
                        scanner.nextLine();

                        while (nota < 1 || nota > 10) {

                            System.out.println("Calificación inválida.");
                            System.out.print("Ingrese una calificación entre 1 y 10: ");

                            nota = scanner.nextInt();
                            scanner.nextLine();
                        }
                        usuario.agregarNota(nombrePeli, nota);
                    } 
					else {
                        System.out.println("No hay espacios disponibles.");
                    }

                    break;

                case 3:
                    if (usuario.cantCalificadas() > 0) {
                        System.out.println("\n----- CALIFICACIONES -----");

                        for (int i = 1; i <= usuario.cantCalificadas();i++) {
                            System.out.println("\nPelícula #" + i);
                            usuario.displayNota(i);
                        }
                    } 
					else {

                        System.out.println("No hay películas calificadas.");
                    }

                    break;

                case 4:
                    if (usuario.cantCalificadas() > 0) {
                        System.out.print("Ingrese el número de película: ");

                        int noPeli = scanner.nextInt();
                        scanner.nextLine();

                        while (noPeli < 1 ||
                               noPeli > usuario.cantCalificadas()) {
                            System.out.println("Número de película inválido.");
                            System.out.print("Ingrese nuevamente: ");

                            noPeli = scanner.nextInt();
                            scanner.nextLine();
                        }

                        usuario.displayNota(noPeli);

                    } else {
                        System.out.println("No hay películas calificadas.");
                    }

                    break;

                case 5:
                    if (usuario.cantCalificadas() > 0) {
                        System.out.print("Ingrese el número de película: ");

                        int noPeli = scanner.nextInt();
                        scanner.nextLine();

                        while (noPeli < 1 ||
                               noPeli > usuario.cantCalificadas()) {
                            System.out.println("Número de película inválido.");
                            System.out.print("Ingrese nuevamente: ");
                            noPeli = scanner.nextInt();
                            scanner.nextLine();
                        }

                        System.out.print("Ingrese la nueva calificación (1 - 10): ");

                        int nuevaNota = scanner.nextInt();
                        scanner.nextLine();

                        while (nuevaNota < 1 || nuevaNota > 10) {
                            System.out.println("Calificación inválida.");
                            System.out.print("Ingrese nuevamente: ");

                            nuevaNota = scanner.nextInt();
                            scanner.nextLine();
                        }

                        usuario.corregirNota(
                                noPeli,
                                nuevaNota
                        );

                        System.out.println("Calificación modificada.");
                    } 
					else {
                        System.out.println("No hay películas calificadas.");
                    }
                    break;

                case 6:

                    if (usuario.cantCalificadas() > 0) {
                        System.out.println("Promedio de calificaciones: "+ usuario.promedioNota());
						} 
					else {
                        System.out.println("No hay películas calificadas.");
                    }
                    break;

                case 7:
                    if (usuario.cantCalificadas() > 0) {
                        System.out.println("Mejor calificación: "+ usuario.maxNota()); 
						System.out.println("Peor calificación: "+ usuario.minNota());
                    } else {

                        System.out.println("No hay películas calificadas.");
                    }
                    break;

                case 8:
                    System.out.println("Películas calificadas: "+ usuario.cantCalificadas());

                    System.out.println("Espacios disponibles: " + usuario.espDisp());
                    break;

                case 9:
                    continuar = false;
                    break;
            }
        }

        scanner.close();
    }
}