//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pel�cula.java
//  @ Date : 12/08/2026
//  @ Author : 
//
//




public class Pelicula {
	private String nombrePeli;
	private int notaPeli;

	public Pelicula() {
    nombrePeli = "PeliDefault";
    notaPeli = 0;
	}

	public Pelicula(String nombrePeli, int notaPeli) {
		this.nombrePeli = nombrePeli;
		this.notaPeli = notaPeli;
	}
	
	public void setNombrePeli(String newNombre) {
		nombrePeli = newNombre;
	}
	
	public String getNombrePeli() {
		return nombrePeli;
	}
	
	public void setNotaPeli(int newNota) {
    notaPeli = newNota;
	}

	public int getNotaPeli() {
    return notaPeli;
	}
}
