//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Usuario.java
//  @ Date : 12/08/2026
//  @ Author : 
//
//




public class Usuario {
	private String nombre;
	private String nombreUsuario;
	private int edad;
	private Pelicula[] cine;


	public Usuario() {
    nombre = "Nombre";
    nombreUsuario = "nombre123";
    edad = 1;

    cine = new Pelicula[10];
	}

	public Usuario(String nombre, String nombreUsuario, int edad) {
		this.nombre = nombre;
    	this.nombreUsuario = nombreUsuario;
    	this.edad = edad;
    	cine = new Pelicula[10];
	}
	
	public void setNombre(String newNombre) {
    nombre = newNombre;
	}

	public String getNombre() {
    	return nombre;
	}

	public void setNombreUsuario(String newNombreUsuario) {
    	nombreUsuario = newNombreUsuario;
	}

	public String getNombreUsuario() {
    	return nombreUsuario;
	}

	public void setEdad(int newEdad) {
    	edad = newEdad;
	}

	public int getEdad() {
    	return edad;
	}
	
	public void agregarNota(String nombrePeli, int newNota) {
    	for (int i = 0; i < cine.length; i++) {
        	if (cine[i] == null) {
            	cine[i] = new Pelicula(nombrePeli, newNota);
            	break;
        	}
    	}
	}
	
	public void displayNota(int noPeli) {
    	System.out.println("Película: " + cine[noPeli - 1].getNombrePeli());
    	System.out.println("Calificación: " + cine[noPeli - 1].getNotaPeli());
	}
	
	public void corregirNota(int noPeli, int nuevaNota) {
	    cine[noPeli - 1].setNotaPeli(nuevaNota);
	}
	
	public float promedioNota() {
    	int suma = 0;
    	int cantidad = 0;

    	for (int i = 0; i < cine.length; i++) {
        	if (cine[i] != null) {
            	suma += cine[i].getNotaPeli();
            	cantidad++;
        		}
    		}
    		if (cantidad == 0) {
        		return 0;
    		}
    		return (float) suma / cantidad;
	}
	
	public int minNota() {
		int menor = 11;
		
		for (int i = 0; i < cine.length; i++) {
			if (cine[i] != null) {
            	if (cine[i].getNotaPeli() < menor) {
                	menor = cine[i].getNotaPeli();
            	}
        	}
    	}

    	return menor;
	}
	
	public int maxNota() {
		int mayor = 0;
		for (int i = 0; i < cine.length; i++) {
			if (cine[i] != null) {
				if (cine[i].getNotaPeli() > mayor) {
					mayor = cine[i].getNotaPeli();
            	}
        	}
    	}
    	return mayor;
	}
	
	public int cantCalificadas() {
		int cantidad = 0;
		
		for (int i = 0; i < cine.length; i++) {
			if (cine[i] != null) {
				cantidad++;
        	}
    	}

    	return cantidad;
	}
	
	public int espDisp() {
    	return 10 - cantCalificadas();
	}
}
